spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.104.119.7:3306/games?useSSL=false
    username: root
    password: uAiqwVwjJ8-i
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.qf.pojo
